{{ if .Values.issuer.acmeHttp.enabled }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.issuer.acmeHttp.name }}
spec:
  acme:
    email: {{ .Values.issuer.acmeHttp.email }}
    server: {{ .Values.issuer.acmeHttp.server }}
    privateKeySecretRef:
      name: example-issuer-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app
spec:
  dnsNames:
    - {{ .Values.app.domain }}
  secretName: ingress-tls
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.issuer.acmeHttp.name }}
{{- end -}}
